# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/alanescudero/CascadeProjects/3Dengine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/alanescudero/CascadeProjects/3Dengine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/alanescudero/CascadeProjects/3Dengine/CMakeFiles /Users/alanescudero/CascadeProjects/3Dengine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/alanescudero/CascadeProjects/3Dengine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_grass

# Build rule for target.
test_grass: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_grass
.PHONY : test_grass

# fast build rule for target.
test_grass/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_grass.dir/build.make CMakeFiles/test_grass.dir/build
.PHONY : test_grass/fast

Engine/Mesh.o: Engine/Mesh.cpp.o
.PHONY : Engine/Mesh.o

# target to build an object file
Engine/Mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_grass.dir/build.make CMakeFiles/test_grass.dir/Engine/Mesh.cpp.o
.PHONY : Engine/Mesh.cpp.o

Engine/Mesh.i: Engine/Mesh.cpp.i
.PHONY : Engine/Mesh.i

# target to preprocess a source file
Engine/Mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_grass.dir/build.make CMakeFiles/test_grass.dir/Engine/Mesh.cpp.i
.PHONY : Engine/Mesh.cpp.i

Engine/Mesh.s: Engine/Mesh.cpp.s
.PHONY : Engine/Mesh.s

# target to generate assembly for a file
Engine/Mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_grass.dir/build.make CMakeFiles/test_grass.dir/Engine/Mesh.cpp.s
.PHONY : Engine/Mesh.cpp.s

Engine/Rendering/Shader.o: Engine/Rendering/Shader.cpp.o
.PHONY : Engine/Rendering/Shader.o

# target to build an object file
Engine/Rendering/Shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_grass.dir/build.make CMakeFiles/test_grass.dir/Engine/Rendering/Shader.cpp.o
.PHONY : Engine/Rendering/Shader.cpp.o

Engine/Rendering/Shader.i: Engine/Rendering/Shader.cpp.i
.PHONY : Engine/Rendering/Shader.i

# target to preprocess a source file
Engine/Rendering/Shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_grass.dir/build.make CMakeFiles/test_grass.dir/Engine/Rendering/Shader.cpp.i
.PHONY : Engine/Rendering/Shader.cpp.i

Engine/Rendering/Shader.s: Engine/Rendering/Shader.cpp.s
.PHONY : Engine/Rendering/Shader.s

# target to generate assembly for a file
Engine/Rendering/Shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_grass.dir/build.make CMakeFiles/test_grass.dir/Engine/Rendering/Shader.cpp.s
.PHONY : Engine/Rendering/Shader.cpp.s

Engine/Rendering/Window.o: Engine/Rendering/Window.cpp.o
.PHONY : Engine/Rendering/Window.o

# target to build an object file
Engine/Rendering/Window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_grass.dir/build.make CMakeFiles/test_grass.dir/Engine/Rendering/Window.cpp.o
.PHONY : Engine/Rendering/Window.cpp.o

Engine/Rendering/Window.i: Engine/Rendering/Window.cpp.i
.PHONY : Engine/Rendering/Window.i

# target to preprocess a source file
Engine/Rendering/Window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_grass.dir/build.make CMakeFiles/test_grass.dir/Engine/Rendering/Window.cpp.i
.PHONY : Engine/Rendering/Window.cpp.i

Engine/Rendering/Window.s: Engine/Rendering/Window.cpp.s
.PHONY : Engine/Rendering/Window.s

# target to generate assembly for a file
Engine/Rendering/Window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_grass.dir/build.make CMakeFiles/test_grass.dir/Engine/Rendering/Window.cpp.s
.PHONY : Engine/Rendering/Window.cpp.s

test_grass.o: test_grass.cpp.o
.PHONY : test_grass.o

# target to build an object file
test_grass.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_grass.dir/build.make CMakeFiles/test_grass.dir/test_grass.cpp.o
.PHONY : test_grass.cpp.o

test_grass.i: test_grass.cpp.i
.PHONY : test_grass.i

# target to preprocess a source file
test_grass.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_grass.dir/build.make CMakeFiles/test_grass.dir/test_grass.cpp.i
.PHONY : test_grass.cpp.i

test_grass.s: test_grass.cpp.s
.PHONY : test_grass.s

# target to generate assembly for a file
test_grass.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_grass.dir/build.make CMakeFiles/test_grass.dir/test_grass.cpp.s
.PHONY : test_grass.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test_grass"
	@echo "... Engine/Mesh.o"
	@echo "... Engine/Mesh.i"
	@echo "... Engine/Mesh.s"
	@echo "... Engine/Rendering/Shader.o"
	@echo "... Engine/Rendering/Shader.i"
	@echo "... Engine/Rendering/Shader.s"
	@echo "... Engine/Rendering/Window.o"
	@echo "... Engine/Rendering/Window.i"
	@echo "... Engine/Rendering/Window.s"
	@echo "... test_grass.o"
	@echo "... test_grass.i"
	@echo "... test_grass.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

